name: CI/CD for Diamond Price Estimator Application

env:
  SERVICE_NAME: diamond-price-estimator
  PROJECT_ID: diamond-app-445820
  DOCKER_IMAGE_URL: europe-west10-docker.pkg.dev/diamond-app-445820/diamond-app/diamond-app

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # - name: Run tests
      #   run: pytest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Google Cloud Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_KEY }}

      - name: Configure GCP project
        run: |
          gcloud config set project ${{ env.PROJECT_ID }}

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Configure Docker
        run: |
          gcloud auth configure-docker europe-west10-docker.pkg.dev

      - name: Build and Push Docker Image
        run: |
          docker build -t diamond-app:latest .
          docker tag diamond-app:latest ${{ env.DOCKER_IMAGE_URL }}:latest
          docker push ${{ env.DOCKER_IMAGE_URL }}:latest

      - name: Deploy to Cloud Run
        run: |
          echo "SERVICE_NAME: ${{ env.SERVICE_NAME }}"
          echo "DOCKER_IMAGE_URL: ${{ env.DOCKER_IMAGE_URL }}"
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image ${{ env.DOCKER_IMAGE_URL }}:latest \
            --platform managed \
            --region europe-west10 \
            --allow-unauthenticated
